server:
  port: 8200
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.5.78:8848
        enabled: true
        weight: 1
    sentinel:
      transport:
        dashboard: 182.92.5.78:8180
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:47.110.32.181}:${DATASOURCE_PORT:3306}/microservices-usercenter?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1nncore.co.ltd}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ymm.microservices.usercenter.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-delete-field: deleted
      id-type: auto

generator:
  filepath: /root/generator

logging:
  level:
    root: warn
    com.ymm.microservices.usercenter: debug
